<?php
/**
 * Defines a class that serves as enumeration of the different language codes
 * that are used as the file names of each po file.
 * 
 * @author Jefferson González
 * @license MIT
 * @link http://github.com/wxphp/peg Source code.
*/

namespace Cms\Enumerations;

/**
 * All languages and its code.
 */
class LanguageCode
{
	const AFRIKAANS = "af";
	const ALBANIAN = "sq";
	const ARABIC_ALGERIA = "ar_DZ";
	const ARABIC_BAHRAIN = "ar_BH";
	const ARABIC_EGYPT = "ar_EG";
	const ARABIC_IRAQ = "ar_IQ";
	const ARABIC_JORDAN = "ar_JO";
	const ARABIC_KUWAIT = "ar_KW";
	const ARABIC_LEBANON = "ar_LB";
	const ARABIC_LIBYA = "ar_LY";
	const ARABIC_MOROCCO = "ar_MA";
	const ARABIC_OMAN = "ar_OM";
	const ARABIC_QATAR = "ar_QA";
	const ARABIC_SAUDI_ARABIA = "ar_SA";
	const ARABIC_SYRIA = "ar_SY";
	const ARABIC_TUNISIA = "ar_TN";
	const ARABIC_UAE = "ar_AE";
	const ARABIC_YEMEN = "ar_YE";
	const ARABIC = "ar";
	const ARMENIAN = "hy";
	const ASSAMESE = "as";
	const AZERI = "az";
	const BASQUE = "eu";
	const BELARUSIAN = "be";
	const BENGALI = "bn";
	const BULGARIAN = "bg";
	const CATALAN = "ca";
	const CHINESE_CHINA = "zh_CN";
	const CHINESE_HONG_KONG_SAR = "zh_HK";
	const CHINESE_MACAU_SAR = "zh_MO";
	const CHINESE_SINGAPORE = "zh_SG";
	const CHINESE_TAIWAN = "zh_TW";
	const CHINESE = "zh";
	const CROATIAN = "hr";
	const CZECH = "cs";
	const DANISH = "da";
	const DIVEHI = "div";
	const DUTCH_BELGIUM = "nl_BE";
	const DUTCH_NETHERLANDS = "nl";
	const ENGLISH_AUSTRALIA = "en_AU";
	const ENGLISH_BELIZE = "en_BZ";
	const ENGLISH_CANADA = "en_CA";
	const ENGLISH_IRELAND = "en_IE";
	const ENGLISH_JAMAICA = "en_JM";
	const ENGLISH_NEW_ZEALAND = "en_NZ";
	const ENGLISH_PHILIPPINES = "en_PH";
	const ENGLISH_SOUTH_AFRICA = "en_ZA";
	const ENGLISH_TRINIDAD = "en_TT";
	const ENGLISH_UNITED_KINGDOM = "en_GB";
	const ENGLISH_UNITED_STATES = "us";
	const ENGLISH_ZIMBABWE = "en_ZW";
	const ENGLISH = "en";
	const ESTONIAN = "et";
	const FAEROESE = "fo";
	const FARSI = "fa";
	const FINNISH = "fi";
	const FRENCH_BELGIUM = "fr_BE";
	const FRENCH_CANADA = "fr_CA";
	const FRENCH_LUXEMBOURG = "fr_LU";
	const FRENCH_MONACO = "fr_MC";
	const FRENCH_SWITZERLAND = "fr_CH";
	const FRENCH_FRANCE = "fr";
	const FYRO_MACEDONIAN = "mk";
	const GAELIC = "gd";
	const GEORGIAN = "ka";
	const GERMAN_AUSTRIA = "de_AT";
	const GERMAN_LIECHTENSTEIN = "de_LI";
	const GERMAN_LUXEMBOURG = "de_LU";
	const GERMAN_SWITZERLAND = "de_CH";
	const GERMAN_GERMANY = "de";
	const GREEK = "el";
	const GUJARATI = "gu";
	const HEBREW = "he";
	const HINDI = "hi";
	const HUNGARIAN = "hu";
	const ICELANDIC = "is";
	const INDONESIAN = "id";
	const ITALIAN_SWITZERLAND = "it_CH";
	const ITALIAN_ITALY = "it";
	const JAPANESE = "ja";
	const KANNADA = "kn";
	const KAZAKH = "kk";
	const KONKANI = "kok";
	const KOREAN = "ko";
	const KYRGYZ = "kz";
	const LATVIAN = "lv";
	const LITHUANIAN = "lt";
	const MALAY = "ms";
	const MALAYALAM = "ml";
	const MALTESE = "mt";
	const MARATHI = "mr";
	const MONGOLIAN_CYRILLIC = "mn";
	const NEPALI_INDIA = "ne";
	const NORWEGIAN_BOKMAL = "no";
	const NORWEGIAN_NYNORSK = "nn_NO";
	const ORIYA = "or";
	const POLISH = "pl";
	const PORTUGUESE_BRAZIL = "pt_BR";
	const PORTUGUESE_PORTUGAL = "pt";
	const PUNJABI = "pa";
	const RHAETO_ROMANIC = "rm";
	const ROMANIAN_MOLDOVA = "ro_MD";
	const ROMANIAN = "ro";
	const RUSSIAN_MOLDOVA = "ru_MD";
	const RUSSIAN = "ru";
	const SANSKRIT = "sa";
	const SERBIAN = "sr";
	const SLOVAK = "sk";
	const SLOVENIAN = "ls";
	const SORBIAN = "sb";
	const SPANISH_ARGENTINA = "es_AR";
	const SPANISH_BOLIVIA = "es_BO";
	const SPANISH_CHILE = "es_CL";
	const SPANISH_COLOMBIA = "es_CO";
	const SPANISH_COSTA_RICA = "es_CR";
	const SPANISH_DOMINICAN_REPUBLIC = "es_DO";
	const SPANISH_ECUADOR = "es_EC";
	const SPANISH_EL_SALVADOR = "es_SV";
	const SPANISH_GUATEMALA = "es_GT";
	const SPANISH_HONDURAS = "es_HN";
	const SPANISH_MEXICO = "es_MX";
	const SPANISH_NICARAGUA = "es_NI";
	const SPANISH_PANAMA = "es_PA";
	const SPANISH_PARAGUAY = "es_PY";
	const SPANISH_PERU = "es_PE";
	const SPANISH_PUERTO_RICO = "es_PR";
	const SPANISH_UNITED_STATES = "es_US";
	const SPANISH_URUGUAY = "es_UY";
	const SPANISH_VENEZUELA = "es_VE";
	const SPANISH_TRADITIONAL_SORT = "es";
	const SUTU = "sx";
	const SWAHILI = "sw";
	const SWEDISH_FINLAND = "sv_FI";
	const SWEDISH = "sv";
	const SYRIAC = "syr";
	const TAMIL = "ta";
	const TATAR = "tt";
	const TELUGU = "te";
	const THAI = "th";
	const TSONGA = "ts";
	const TSWANA = "tn";
	const TURKISH = "tr";
	const UKRAINIAN = "uk";
	const URDU = "ur";
	const UZBEK = "uz";
	const VIETNAMESE = "vi";
	const XHOSA = "xh";
	const YIDDISH = "yi";
	const ZULU = "zu";
    
    public static function GetAll()
    {
        $labels = array(
            'af'    => 'Afrikaans',
            'sq'    => 'Albanian',
            'ar_DZ' => 'Arabic Algeria',
            'ar_BH' => 'Albanian',
            'ar_EG' => 'Arabic Egypt',
            'ar_IQ' => 'Arabic Iraq',
            'ar_JO' => 'Arabic Jordan',
            'ar_KW' => 'Arabic Kuwait',
            'ar_LB' => 'Arabic Lebanon',
            'ar_LY' => 'Arabic Libya',
            'ar_MA' => 'Arabic Morocco',
            'ar_OM' => 'Arabic Oman',
            'ar_QA' => 'Arabic Qatar',
            'ar_SA' => 'Arabic Saudi Arabia',
            'ar_SY' => 'Arabic Syria',
            'ar_TN' => 'Arabic Tunisia',
            'ar_AE' => 'Arabic UAE',
            'ar_YE' => 'Arabic Yemen',
            'ar'    => 'Arabic',
            'hy'    => 'Aremenian',
            'as'    => 'Assamese',
            'az'    => 'Azeria',
            'eu'    => 'Basque',
            'be'    => 'Belarusian',
            'bn'    => 'Bengali',
            'bg'    => 'Bulgarian',
            'ca'    => 'Catalan',
            'zh_CN' => 'Chinese China',
            'zh_HK' => 'Chinese Hong Kong',
            'zh_MO' => 'Chinese Macau',
            'zh_SG' => 'Chinese Singapore',
            'zh_TW' => 'Chinese Taiwan',
            'zh'    => 'Chinese',
            'hr'    => 'Croattian',
            'cs'    => 'Czech',
            'da'    => 'Danish',
            'div'   => 'Divehi',
            'nl_BE' => 'Dutch Belgium',
            'nl'    => 'Dutch Netherlands',
            'en_AU' => 'English Australia',
            'en_BZ' => 'English Belize',
            'en_CA' => 'English Canada',
            'en_IE' => 'English Ireland',
            'en_JM' => 'English Jamaica',
            'en_NZ' => 'English New Zealand',
            'en_PH' => 'English Philippines',
            'en_ZA' => 'English South Africa',
            'en_TT' => 'English Trinida',
            'en_GB' => 'English United Kindgom',
            'en_US' => 'English United States',
            'en'    => 'English',
            'et'    => 'Estonian',
            'fo'    => 'Faeroese',
            'fa'    => 'Farsi',
            'fi'    => 'Finnish',
            'fr_BE' => 'French Belgium',
            'fr_CA' => 'French Canada',
            'fr_LU' => 'French Luxemburg',
            'fr_MC' => 'French Monaco',
            'fr_CH' => 'French Switzerland',
            'fr'    => 'French France',
            'mk'    => 'Fyro Macedonian',
            'gd'    => 'Gaelic',
            'ka'    => 'Georgian',
            'de_AT' => 'German Austria',
            'de_LI' => 'German Liechtenstein',
            'de_LU' => 'German Luxembourg',
            'de_CH' => 'German Switzerland',
            'de'    => 'German Germany',
            'el'    => 'Greek',
            'gu'    => 'Gujarati',
            'he'    => 'Hebrew',
            'hi'    => 'Hindi',
            'hu'    => 'Hungarian',
            'is'    => 'Icelandic',
            'id'    => 'Indonesian',
            'it_CH' => 'Italian Switzerland',
            'it'    => 'Italian Italy',
            'ja'    => 'Japanese',
            'kn'    => 'Kannada',
            'kk'    => 'Kazakh',
            'kok'   => 'Konkani',
            'ko'    => 'Korean',
            'kz'    => 'Kyrgyz',
            'lv'    => 'Latvian',
            'lt'    => 'Lithuanian',
            'ms'    => 'Malay',
            'ml'    => 'Malayalam',
            'mt'    => 'Maltese',
            'mr'    => 'Marathi',
            'mn'    => 'Mongolian Cyrillic',
            'ne'    => 'Nepali India',
            'no'    => 'Noregian Bokmal',
            'no_NO' => 'Nnoregian Nynorsk',
            'or'    => 'Oriya',
            'pl'    => 'Polish',
            'pt_BR' => 'Portuguese Brazil',
            'pt'    => 'Portuguese Portugal',
            'pa'    => 'Punjabi',
            'rm'    => 'Rhaeto Romanic',
            'ro_MD' => 'Romanian Moldova',
            'ro'    => 'Romanian',
            'ru_MD' => 'Russian Moldova',
            'ru'    => 'Russian',
            'sa'    => 'Sanskrit',
            'sr'    => 'Serbian',
            'sk'    => 'Slovak',
            'ls'    => 'Slovenian',
            'sb'    => 'Sorbian',
            'es_AR' => 'Spanish Argentina',
            'es_BO' => 'Spanish Bolivia',
            'es_CL' => 'Spanish Chile',
            'es_CO' => 'Spanish Colombia',
            'es_CR' => 'Spanish Costa Rica',
            'es_DO' => 'Spanish Dominical Republic',
            'es_EC' => 'Spanish Ecuador',
            'es_SV' => 'Spanish El Salvador',
            'es_GT' => 'Spanish Guatemala',
            'es_HN' => 'Spanish Honduras',
            'es_MX' => 'Spanish Mexico',
            'es_NI' => 'Spanish Nicaragua',
            'es_PA' => 'Spanish Panama',
            'es_PY' => 'Spanish Paraguay',
            'es_PE' => 'Spanish Peru',
            'es_PR' => 'Spanish Puerto Rico',
            'es_US' => 'Spanish United States',
            'es_UY' => 'Spanish Uruguay',
            'es'    => 'Spanish Traditional Sort',
            'sx'    => 'Sutu',
            'sw'    => 'Swahili',
            'sv_FI' => 'Swedish Finland',
            'sv'    => 'Swedish',
            'syr'   => 'Syriac',
            'ta'    => 'Tamil',
            'tt'    => 'Tatar',
            'te'    => 'Telugu',
            'th'    => 'Thai',
            'ts'    => 'Tsonga',
            'tn'    => 'Tswana',
            'tr'    => 'Turkish',
            'uk'    => 'Ukrainian',
            'ur'    => 'Urdu',
            'uz'    => 'Uzbek',
            'vi'    => 'Vietnamese',
            'xh'    => 'Xhosa',
            'yi'    => 'Yiddish',
            'zu'    => 'Zulu'
        );
        
        return $labels;
    }
    
    public static function GetLabel($language_code)
    {
        return self::GetAll()[$language_code];
    }
}

?>
